### ISSUE TITLE
default value of CVMFS_CACHE_BASE set in cc_cvmfs.py (cern-cloudinit-latest-5-5.2)

### ISSUE THREAD

**Issue by rptaylor** [cjdcordeiro/cloud-init-cern#1]
Hello,

See https://github.com/hep-gc/cloudinit-userdata/issues/23

Currently, in cern-cloudinit-latest-5-5.2, cc_cvmfs.py is setting a default value which applies when the  YAML files do not contain CVMFS_CACHE_BASE:

```
'CVMFS_CACHE_BASE' : '/scratch/cvmfs-cache',
```

However, if the YAML files do not contain any value for CVMFS_CACHE_BASE, then the cern-cloudinit scripts should not set any value either. Then CVMFS_CACHE_BASE should be absent from /etc/cvmfs/default.local, so CVMFS will run normally using the default location for CVMFS_CACHE_BASE, which is /var/lib/cvmfs (from /etc/cvmfs/default.conf) .

Thanks!

**Comment by cjdcordeiro** [comment]
Hi @rptaylor, 

this parameter is set by default to be /scratch/cvmfs-cache. It was decided to be like that for consistency/convention purposes since /scratch is usually also used for Condor and recently for benchmarking as well. It is basically considered to be a common working area.

If you think this approach is wrong then we can reconsider and discuss it. But in your particular case can't you just set up CVMFS_CACHE_BASE in you yaml to be /var/lib/cvmfs?

Cheers

**Comment by rptaylor** [comment]
Hi Cristovao!

Actually the default location for the condor working directory is /var/lib/condor/ . Just as for CVMFS, one could change it to /scratch, but I wouldn't consider it a standard location as it is not in the FHS.
Sure, we can set CVMFS_CACHE_BASE to anything in the YAML. The location of the directory doesn't really matter one way or the other. What I would prefer is the ability to not set it at all so we don't have to care either way, and it is left up to CVMFS to use the default location.

Thanks!

**Comment by rptaylor** [comment]
Hi,

I also noticed that "/scratch" is hardcoded into the cc_cvmfs.py file in a few places. However I think CVMFS may create and chown the needed cache directory, so this might be redundant.

**Comment by cjdcordeiro** [comment]
Hi @rptaylor 

I've commented the default CACHE_BASE variable. So it shall not be written into .local unless you provide it.

PLEASE NOTICE, that all of these changes are now in https://gitlab.cern.ch/chdoming/cloud-init-cern/blob/devel/cern-cloudinit/cloudinit/config/cc_cvmfs.py as we are moving into GitLab@CERN. This repository is soon outdated.

The new RPMs with the latest changes will be built soon and then is up to the CernVM team to include the new RPMs.

Cheers,
Cris
